version: '3'

services:
  client_api:
    image: client_api
#    build:
#      context: .
#      args:
#        - SERVICE=client_api
#        - CONFIG=tmpl
    env_file:
      - ./env/template.env
    ports:
      - 8080:8080
    volumes:
      - './ports.json:/ports.json'
    depends_on:
      - port_domain_service
    networks:
      ps_net:

  port_domain_service:
    image: port_domain_service
#    build:
#      context: ./
#      args:
#        - SERVICE=port_domain_service
#        - CONFIG=tmpl
    env_file:
      - ./env/template.env
    ports:
      - 8090:8090
    depends_on:
      - postgres
    networks:
      ps_net:

  postgres:
    image: postgres:12-alpine
    env_file:
      - ./env/template.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      ps_net:

networks:
  ps_net: {}

volumes:
  postgres_data: {}
