log:
  app_name: todo
  level: "env:LOG_LEVEL"
  add_trace: true
  sentry: ""
  json: false

db: &db
  driver: 'postgres'
  host: '127.0.0.1'
  user: 'raw:user'
  password: 'env:POSTGRES_PASSWORD'
  name: 'price_storage'

  init_timeout: 60 # in seconds
  auto_migrate: true
  wait_for_db: true
  #  optional connection parameters
  params:
    max_idle: 100
    max_open: 300
    max_lifetime: 3200 # in milliseconds

workers:
  enable:
    - api_server

  api_server:
    db:
      <<: *db
    api:
      host: localhost
      port: 8080
      enable_cors: true
      api_request_timeout: 60
    dev_mode: true
  # END of api_server >>/
